import {Component, Input, ChangeDetectionStrategy} from '@angular/core';
import {ps3CaseStyle, caseRegion} from '../../shared/ps3-case';
@Component({selector:'app-game-cover',standalone:true,changeDetection:ChangeDetectionStrategy.OnPush,
 template:`<span class="cover" [class.box]="style !== 'none'" [class.legacy]="style === 'legacy'" [class.blue]="style === 'blue'" [attr.data-region]="market" [attr.title]="style !== 'none' ? 'Стилизация коробки PS3 по региону и дате релиза' : null">
 @if(style !== 'none'){<span class="spine" aria-hidden="true"><span class="spine-logo">PS3</span><span class="spine-title">{{name}}</span></span><span class="rim" aria-hidden="true">Blu-ray Disc</span><span class="brand" aria-hidden="true">{{style === 'legacy' ? 'PLAYSTATION 3' : 'PS3'}}</span>}
 <span class="art">@if(src && failed !== src){<img [src]="src" [alt]="name" [attr.loading]="priority ? 'eager' : 'lazy'" decoding="async" [attr.fetchpriority]="priority ? 'high' : 'auto'" (error)="failed = src"/>}@else{<span class="empty">Нет изображения</span>}</span></span>`,
 styles:[`:host{display:block;width:100%;height:100%;min-width:0;container-type:inline-size}.cover{display:block;position:relative;width:100%;height:100%;overflow:hidden;box-sizing:border-box;aspect-ratio:3/4}.art{display:block;width:100%;height:100%;min-height:0}img{display:block;width:100%;height:100%;object-fit:cover}.empty{display:grid;place-items:center;height:100%;background:#122132;color:#a3b8cb;font:12px system-ui}.box{padding:15% 3% 3% 12%;border:1px solid #c4cbd0;border-radius:5% 3% 3% 5%;background:linear-gradient(100deg,#88969f,#e2e6e999 5%,#a4b2bd 7%,#c2ccd2 98%,#6d7b87);box-shadow:inset 2px 0 3px #fff8,2px 3px 5px #0006}.rim{position:absolute;top:1%;left:16%;height:4%;color:#34414d;font:italic 6px sans-serif}.brand{position:absolute;left:12%;right:3%;top:6%;height:9%;background:linear-gradient(#27292d,#08090a);color:white;display:flex;align-items:center;padding-left:5%;font:italic bold clamp(10px,2vw,22px) Arial;letter-spacing:.06em}.blue .brand{background:linear-gradient(#1176b9,#00416c)}.legacy{padding-top:11%;padding-left:22%}.legacy .brand{top:11%;bottom:3%;left:12%;right:auto;height:auto;width:10%;padding:0;writing-mode:vertical-rl;transform:rotate(180deg);font:normal 11px Arial;letter-spacing:.13em}.legacy .rim{top:3%;font-size:7px}.legacy[data-region=america] .brand{background:linear-gradient(90deg,#491a1e,#17171b)}.legacy[data-region=japan] .brand{background:linear-gradient(90deg,#29292b,#050505)}.legacy[data-region=europe] .brand{background:linear-gradient(90deg,#44464b,#17181c)}.spine{position:absolute;left:1%;top:6%;bottom:3%;width:9%;display:flex;flex-direction:column;align-items:stretch;background:linear-gradient(90deg,#07090c,#30343b 60%,#0b1016);box-shadow:inset -1px 0 1px #0009,1px 0 1px #fff6;overflow:hidden}.spine-logo{display:flex;align-items:center;justify-content:center;flex:none;height:8%;min-height:14px;color:#fff;background:#111319;font:italic bold 4.5cqi Arial;letter-spacing:-.08em}.spine-title{position:absolute;top:12%;left:0;width:100%;height:85%;box-sizing:border-box;writing-mode:vertical-rl;text-orientation:mixed;text-align:start;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;padding:1.5cqw 0;color:#e8edf1;font:500 4cqw/9cqw Arial;letter-spacing:.02em}.legacy .spine{background:#fff}.legacy .spine-logo{background:linear-gradient(#d91f30,#9d0717);font-style:normal;color:white}.legacy .spine-title{color:#161616}.blue .spine-logo{background:linear-gradient(#1176b9,#00416c)}`]})
export class GameCoverComponent {
 @Input() src:string|null|undefined; @Input() name=''; @Input() platform:number|null|undefined;
 @Input() region:string|number|null|undefined; @Input() date:number|null|undefined; @Input() digital=false; @Input() priority=false;
 failed:string|null|undefined;
 get market(){return caseRegion(this.region);}
 get style(){return ps3CaseStyle(this.platform,this.region,this.date,this.name,this.digital);}
}
