import { ComponentFixture, TestBed } from '@angular/core/testing';
import { HttpTestingController } from '@angular/common/http/testing';
import { Store } from '@ngxs/store';
import { TEST_PROVIDERS } from '@app/testing/test-providers';
import { CollectorsActions } from '@app/states/collectors/states/collectors-actions';
import { CollectorPropertiesComponent } from './collector-properties.component';
const items=Array.from({length:49},(_,i)=>({release_id:i+1,product_id:i+1,product_name:`Release ${i+1}`,platform_id:48,platform_name:'PS4',region_id:1,region_name:'europe',serial:['CUSA-00001','CUSA-00002'],selected_serial:i===0?'CUSA-00002':null,release_date:1000,image_url:null,price:null,cib:true}));
describe('Collector server pages',()=>{
 let fixture:ComponentFixture<CollectorPropertiesComponent>, http:HttpTestingController, store:Store;
 beforeEach(()=>{vi.useFakeTimers();vi.spyOn(window,'scrollTo').mockImplementation(()=>{});TestBed.configureTestingModule({imports:[CollectorPropertiesComponent],providers:TEST_PROVIDERS});http=TestBed.inject(HttpTestingController);store=TestBed.inject(Store);store.dispatch(new CollectorsActions.SelectCollector('alice'));fixture=TestBed.createComponent(CollectorPropertiesComponent);fixture.detectChanges();});
 afterEach(()=>{fixture.destroy();http.verify({ignoreCancelled:true});vi.useRealTimers();vi.restoreAllMocks();});
 function pending(kind='collection'){vi.advanceTimersByTime(1);return http.expectOne(r=>r.url===`/api/library/${kind}`);}
 function flush(req:ReturnType<typeof pending>,data=items){req.flush({items:data.slice(Number(req.request.params.get('offset')),Number(req.request.params.get('offset'))+Number(req.request.params.get('limit'))),total_count:data.length,unfiltered_total:data.length,platform_ids:[48],owned_regions:{europe:49}});fixture.detectChanges();}
 it('requests only 24 read-only cards and shows the selected serial',()=>{const req=pending();expect(req.request.params.get('login')).toBe('alice');expect(req.request.params.get('limit')).toBe('24');flush(req);expect(fixture.nativeElement.querySelectorAll('app-release-card')).toHaveLength(24);expect(fixture.nativeElement.querySelector('.edit-button')).toBeNull();expect(fixture.nativeElement.querySelector('.incomplete')).toBeNull();expect(fixture.nativeElement.querySelector('app-release-card').textContent).toContain('CUSA-00002');expect(fixture.nativeElement.textContent).not.toContain('Куплено за');fixture.componentInstance.page(3);const page=pending();expect(page.request.params.get('offset')).toBe('48');flush(page);expect(fixture.nativeElement.querySelectorAll('app-release-card')).toHaveLength(1);});
 it('preserves release-specific navigation and keeps all unselected serials accessible',()=>{flush(pending());const cards=fixture.nativeElement.querySelectorAll('app-release-card');expect(cards[0].querySelector('a').getAttribute('href')).toBe('/products/1;platform=48');expect(cards[1].querySelector('details')).not.toBeNull();cards[1].querySelector('summary').click();expect(cards[1].textContent).toContain('CUSA-00002');});
 it('cancels a pending request on collector change and keeps independent pages',()=>{flush(pending());fixture.componentInstance.page(3);flush(pending());fixture.componentInstance.retry();const stale=pending();store.dispatch(new CollectorsActions.SelectCollector('bob'));const bob=pending();expect(stale.cancelled).toBe(true);expect(bob.request.params.get('login')).toBe('bob');expect(bob.request.params.get('offset')).toBe('0');flush(bob);store.dispatch(new CollectorsActions.SelectCollector('alice'));const alice=pending();expect(alice.request.params.get('offset')).toBe('48');flush(alice);});
 it('pages sales too, retries failures and never loads the full sale list',()=>{flush(pending());fixture.componentInstance.selectTab('wts');const req=pending('wts');expect(req.request.params.get('limit')).toBe('24');req.flush('',{status:500,statusText:'Error'});fixture.detectChanges();expect(fixture.nativeElement.textContent).toContain('Не удалось загрузить');fixture.componentInstance.retry();flush(pending('wts'));expect(fixture.nativeElement.querySelector('.edit-button')).toBeNull();fixture.componentInstance.page(2);const page=pending('wts');expect(page.request.params.get('offset')).toBe('24');flush(page);});
 it('sends filters and sort to the server with a page reset',()=>{flush(pending());fixture.componentInstance.page(3);flush(pending());fixture.componentInstance.selectPlatform(48);let req=pending();expect(req.request.params.get('offset')).toBe('0');expect(req.request.params.get('cat')).toBe('48');flush(req);fixture.componentInstance.toggleRegion('europe');req=pending();expect(req.request.params.get('regions')).toBe('europe');flush(req);fixture.componentInstance.sort('date');req=pending();expect(req.request.params.get('sort')).toBe('date');flush(req);fixture.componentInstance.selectPlatform(null);req=pending();expect(req.request.params.has('cat')).toBe(false);expect(req.request.params.get('regions')).toBe('');flush(req);});
});
